// <auto-generated />
namespace ASPMVC_EF_Music.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change21));
        
        string IMigrationMetadata.Id
        {
            get { return "201710301134207_change21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
